[versions]
compose = "2024.11.00"

[libraries]
bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
animation = { module = "androidx.compose.animation:animation" }
foundation = { module = "androidx.compose.foundation:foundation" }
material3 = { module = "androidx.compose.material3:material3" }
material-motion = { module = "io.github.fornewid:material-motion-compose-core", version = "1.0.7" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
icons = { module = "androidx.compose.material:material-icons-extended" }
webview = { module = "io.github.kevinnzou:compose-webview", version = "0.33.6" }

[bundles]
compose = [ "animation", "foundation", "material3", "material-motion", "ui-tooling-preview", "icons" ]
